# Generated by Django 5.0.6 on 2024-07-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='id2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
