# Generated by Django 5.0.6 on 2024-07-05 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_vacancy_id2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='id2',
        ),
    ]
