# Generated by Django 5.0.6 on 2024-07-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0005_remove_vacancy_description_vacancy_salary_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='salary_max',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='salary_min',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requirement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='responsibility',
            field=models.TextField(blank=True, null=True),
        ),
    ]
