# Generated by Django 5.0.6 on 2024-07-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0006_remove_vacancy_salary_max_remove_vacancy_salary_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='salary_max',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_min',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
