# Generated by Django 5.0.6 on 2024-07-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0007_vacancy_salary_max_vacancy_salary_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='alternate_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
