# Generated by Django 5.0.6 on 2024-07-05 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0008_vacancy_alternate_url_vacancy_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='published_at',
        ),
    ]
