# Generated by Django 5.0.6 on 2024-07-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0012_remove_vacancy_alternate_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='alternate_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
