# Generated by Django 5.0.6 on 2024-07-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0013_vacancy_alternate_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='employment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
